### ISSUE TITLE
folio-even is offset when left aligned, happens with new update of resilient.sile

### ISSUE THREAD

**Issue by no-vici** [Omikhleia/resilient.sile#42]
Hi there,

Last night, I updated resilient.sile and this happened, this did not happen with earlier versions.

I still can't where the problem comes from.

Before:
![image](https://user-images.githubusercontent.com/113570767/236759162-de310704-3999-4103-b8d7-c7af4bcd3710.png)

After the update:
![image](https://user-images.githubusercontent.com/113570767/236759480-5a1f63c7-d187-4a8b-aefa-48ef39715210.png)

My folio style is as follows:

```
folio-even:
  inherit: "folio-base"
  origin: "resilient.book"
  style:
    font:
      size: "0.80em"
    # paragraph:
      # align: "left"

folio-odd:
  inherit: "folio-base"
  origin: "resilient.book"
  style:
    font:
      size: "0.80em"
    paragraph:
      align: "right"

```

**Comment by Omikhleia** [comment]
Greetings,
Good catch... There was an error in the default generated style (#30)
It was introduced in 2.0.0 and I minimally fixed it in 2.0.1 (so it now generated the correct defaults), but earlier users are indeed affected (... and you are probably one of these very few early hard-core users :cat !), since existing styles are not re-generated...

On existing style files, theses styles should be fixed manually:
```
folio-even:
  inherit: "folio-base"
  origin: "resilient.book"
  style:
    paragraph:
      align: "left"
      before:
        indent: false

folio-odd:
  inherit: "folio-base"
  origin: "resilient.book"
  style:
    paragraph:
      align: "right"
      before:
        indent: false
```

FWIW, The root cause at the core of it was whether left/right alignment should have a paragraph indent or not... SILE's ragged environment don't have the parindent, but don't allow nesting (i.e. they always take 100% of the line width even if they were in an indented environment). So I re-implemented them to support nesting and used that in the styling methods... But I kept the paragraph indent, because there are cases when it might be needed (though not on folios, obviously). I am still not fully satisfied with how paragraph indents are managed (and to be complete, how to properly manage left and right skips), to be honest -- so I just went for the minimal fix here (= fix the default style for brand new documents).

**Comment by Omikhleia** [comment]
By the way, `header-odd` and `header-even` may need the same style-fixing too.

**Comment by Omikhleia** [comment]
I should have mentioned that more clearly in the Release notes... Just did it (https://github.com/Omikhleia/resilient.sile/releases/tag/v2.0.1), sorry for the inconvenience.

**Comment by no-vici** [comment]
> Greetings, Good catch... There was an error in the default generated style (#30) It was introduced in 2.0.0 and I minimally fixed it in 2.0.1 (so it now generates the correct defaults), but earlier users are indeed affected (... and you are probably one of these very few early hard-core early adopters cat !), since existing styles are not re-generated...

I've just seen what you changed for the `init.lua`, thank you for your clear explanation and the fix. Only the author knew what caused the problem. At first, I thought the `frametrick` or the `offset` parameter caused the shift, disabling them did not worked out, so the last resource is reaching out to you.

The logics of the `style` package are very advanced, I still don't quite get it, will have to read your code a dozen of times. You should write a book about how to code in Lua for SILE, diving into the underneath coding part is quite a fun experience, and you know it all. I do know that you don't expect us, the end users, mention too much about the internal bits ;) and I don't mean to be offensive ;)

**Comment by no-vici** [comment]
> By the way, `header-odd` and `header-even` may need the same style-fixing too ...

The header wasn't affected for my case ;)
